

SELECT CART_ID, CASE WHEN 
(SELECT SUM(PRICE) as  
from CART_PRODUCTS
GROUP BY
CART_ID) <= C.MINIMAL_REQUIREMENT))
then 1 else 0 end as ABUSED
FROM CART_PRODUCTS P 
GROUP BY CART_ID
JOIN COUPONS C ON P.CART_ID = C.CART_ID


