CREATE TABLE APP_ROW_KEY (
	SCHED_KEY VARCHAR(50) NOT NULL,
	ROW_KEY VARCHAR(50) NOT NULL,
	COLLECT_DATETIME VARCHAR(50),
	STATUS CHAR(1) DEFAULT 'Y',	-- Y:정상,E:오류
	PAGE NUMBER(7),
	ISNEW CHAR(1) DEFAULT 'Y',	-- Y:신규,N:처리완료
	MESSAGE VARCHAR(3000),
	PARAMS VARCHAR(1000)
);

COMMENT ON TABLE APP_ROW_KEY IS '스케줄과 데이터 키 관리';
COMMENT ON COLUMN APP_ROW_KEY.SCHED_KEY IS '스케줄 키';
COMMENT ON COLUMN APP_ROW_KEY.ROW_KEY IS '데이터 키';

CREATE UNIQUE INDEX XPK_APP_ROW_KEY ON TIBERO.APP_ROW_KEY (
	SCHED_KEY ASC,
	COLLECT_DATETIME,
	ROW_KEY ASC
);

ALTER TABLE APP_ROW_KEY ADD CONSTRAINT XPK_APP_ROW_KEY
PRIMARY KEY (
	SCHED_KEY,
	COLLECT_DATETIME,
	ROW_KEY
);



CREATE TABLE APP_XML_ADMRUL_DATA (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    TAG_NAME VARCHAR(100),
    TAG_VALUE CLOB,
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_ADMRUL_DATA ON APP_XML_ADMRUL_DATA (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC
);

ALTER TABLE APP_XML_ADMRUL_DATA ADD CONSTRAINT XPK_APP_XML_ADMRUL_DATA
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ
);

CREATE TABLE APP_XML_ADMRUL_DATA_ATTR (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    SEQ NUMBER(10) NOT NULL,
    ATTR_NAME VARCHAR(100),
    ATTR_VALUE VARCHAR(200),
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_ADMRUL_DATA_ATTR ON APP_XML_ADMRUL_DATA_ATTR (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC,
    SEQ ASC
);

ALTER TABLE APP_XML_ADMRUL_DATA_ATTR ADD CONSTRAINT XPK_APP_XML_ADMRUL_DATA_ATTR
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ,
    SEQ
);

CREATE TABLE APP_XML_ADMRUL_LIST (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    TAG_NAME VARCHAR(100),
    TAG_VALUE CLOB,
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_ADMRUL_LIST ON APP_XML_ADMRUL_LIST (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC
);

ALTER TABLE APP_XML_ADMRUL_LIST ADD CONSTRAINT XPK_APP_XML_ADMRUL_LIST
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ
);

CREATE TABLE APP_XML_ADMRUL_LIST_ATTR (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    SEQ NUMBER(10) NOT NULL,
    ATTR_NAME VARCHAR(100),
    ATTR_VALUE VARCHAR(200),
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_ADMRUL_LIST_ATTR ON APP_XML_ADMRUL_LIST_ATTR (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC,
    SEQ ASC
);

ALTER TABLE APP_XML_ADMRUL_LIST_ATTR ADD CONSTRAINT XPK_APP_XML_ADMRUL_LIST_ATTR
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ,
    SEQ
);

CREATE TABLE APP_XML_DETC_DATA (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    TAG_NAME VARCHAR(100),
    TAG_VALUE CLOB,
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_DETC_DATA ON APP_XML_DETC_DATA (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC
);

ALTER TABLE APP_XML_DETC_DATA ADD CONSTRAINT XPK_APP_XML_DETC_DATA
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ
);

CREATE TABLE APP_XML_DETC_DATA_ATTR (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    SEQ NUMBER(10) NOT NULL,
    ATTR_NAME VARCHAR(100),
    ATTR_VALUE VARCHAR(200),
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_DETC_DATA_ATTR ON APP_XML_DETC_DATA_ATTR (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC,
    SEQ ASC
);

ALTER TABLE APP_XML_DETC_DATA_ATTR ADD CONSTRAINT XPK_APP_XML_DETC_DATA_ATTR
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ,
    SEQ
);

CREATE TABLE APP_XML_DETC_LIST (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    TAG_NAME VARCHAR(100),
    TAG_VALUE CLOB,
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_DETC_LIST ON APP_XML_DETC_LIST (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC
);

ALTER TABLE APP_XML_DETC_LIST ADD CONSTRAINT XPK_APP_XML_DETC_LIST
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ
);

CREATE TABLE APP_XML_DETC_LIST_ATTR (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    SEQ NUMBER(10) NOT NULL,
    ATTR_NAME VARCHAR(100),
    ATTR_VALUE VARCHAR(200),
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_DETC_LIST_ATTR ON APP_XML_DETC_LIST_ATTR (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC,
    SEQ ASC
);

ALTER TABLE APP_XML_DETC_LIST_ATTR ADD CONSTRAINT XPK_APP_XML_DETC_LIST_ATTR
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ,
    SEQ
);

CREATE TABLE APP_XML_EFLAW_DATA (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    TAG_NAME VARCHAR(100),
    TAG_VALUE CLOB,
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_EFLAW_DATA ON APP_XML_EFLAW_DATA (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC
);

ALTER TABLE APP_XML_EFLAW_DATA ADD CONSTRAINT XPK_APP_XML_EFLAW_DATA
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ
);

CREATE TABLE APP_XML_EFLAW_DATA_ATTR (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    SEQ NUMBER(10) NOT NULL,
    ATTR_NAME VARCHAR(100),
    ATTR_VALUE VARCHAR(200),
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_EFLAW_DATA_ATTR ON APP_XML_EFLAW_DATA_ATTR (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC,
    SEQ ASC
);

ALTER TABLE APP_XML_EFLAW_DATA_ATTR ADD CONSTRAINT XPK_APP_XML_EFLAW_DATA_ATTR
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ,
    SEQ
);

CREATE TABLE APP_XML_EFLAW_LIST (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    TAG_NAME VARCHAR(100),
    TAG_VALUE CLOB,
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_EFLAW_LIST ON APP_XML_EFLAW_LIST (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC
);

ALTER TABLE APP_XML_EFLAW_LIST ADD CONSTRAINT XPK_APP_XML_EFLAW_LIST
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ
);

CREATE TABLE APP_XML_EFLAW_LIST_ATTR (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    SEQ NUMBER(10) NOT NULL,
    ATTR_NAME VARCHAR(100),
    ATTR_VALUE VARCHAR(200),
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_EFLAW_LIST_ATTR ON APP_XML_EFLAW_LIST_ATTR (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC,
    SEQ ASC
);

ALTER TABLE APP_XML_EFLAW_LIST_ATTR ADD CONSTRAINT XPK_APP_XML_EFLAW_LIST_ATTR
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ,
    SEQ
);

CREATE TABLE APP_XML_ELAW_DATA (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    TAG_NAME VARCHAR(100),
    TAG_VALUE CLOB,
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_ELAW_DATA ON APP_XML_ELAW_DATA (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC
);

ALTER TABLE APP_XML_ELAW_DATA ADD CONSTRAINT XPK_APP_XML_ELAW_DATA
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ
);

CREATE TABLE APP_XML_ELAW_DATA_ATTR (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    SEQ NUMBER(10) NOT NULL,
    ATTR_NAME VARCHAR(100),
    ATTR_VALUE VARCHAR(200),
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_ELAW_DATA_ATTR ON APP_XML_ELAW_DATA_ATTR (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC,
    SEQ ASC
);

ALTER TABLE APP_XML_ELAW_DATA_ATTR ADD CONSTRAINT XPK_APP_XML_ELAW_DATA_ATTR
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ,
    SEQ
);

CREATE TABLE APP_XML_ELAW_LIST (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    TAG_NAME VARCHAR(100),
    TAG_VALUE CLOB,
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_ELAW_LIST ON APP_XML_ELAW_LIST (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC
);

ALTER TABLE APP_XML_ELAW_LIST ADD CONSTRAINT XPK_APP_XML_ELAW_LIST
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ
);

CREATE TABLE APP_XML_ELAW_LIST_ATTR (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    SEQ NUMBER(10) NOT NULL,
    ATTR_NAME VARCHAR(100),
    ATTR_VALUE VARCHAR(200),
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_ELAW_LIST_ATTR ON APP_XML_ELAW_LIST_ATTR (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC,
    SEQ ASC
);

ALTER TABLE APP_XML_ELAW_LIST_ATTR ADD CONSTRAINT XPK_APP_XML_ELAW_LIST_ATTR
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ,
    SEQ
);

CREATE TABLE APP_XML_EXPC_DATA (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    TAG_NAME VARCHAR(100),
    TAG_VALUE CLOB,
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_EXPC_DATA ON APP_XML_EXPC_DATA (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC
);

ALTER TABLE APP_XML_EXPC_DATA ADD CONSTRAINT XPK_APP_XML_EXPC_DATA
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ
);

CREATE TABLE APP_XML_EXPC_DATA_ATTR (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    SEQ NUMBER(10) NOT NULL,
    ATTR_NAME VARCHAR(100),
    ATTR_VALUE VARCHAR(200),
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_EXPC_DATA_ATTR ON APP_XML_EXPC_DATA_ATTR (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC,
    SEQ ASC
);

ALTER TABLE APP_XML_EXPC_DATA_ATTR ADD CONSTRAINT XPK_APP_XML_EXPC_DATA_ATTR
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ,
    SEQ
);

CREATE TABLE APP_XML_EXPC_LIST (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    TAG_NAME VARCHAR(100),
    TAG_VALUE CLOB,
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_EXPC_LIST ON APP_XML_EXPC_LIST (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC
);

ALTER TABLE APP_XML_EXPC_LIST ADD CONSTRAINT XPK_APP_XML_EXPC_LIST
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ
);

CREATE TABLE APP_XML_EXPC_LIST_ATTR (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    SEQ NUMBER(10) NOT NULL,
    ATTR_NAME VARCHAR(100),
    ATTR_VALUE VARCHAR(200),
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_EXPC_LIST_ATTR ON APP_XML_EXPC_LIST_ATTR (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC,
    SEQ ASC
);

ALTER TABLE APP_XML_EXPC_LIST_ATTR ADD CONSTRAINT XPK_APP_XML_EXPC_LIST_ATTR
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ,
    SEQ
);

CREATE TABLE APP_XML_LSTRM_DATA (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    TAG_NAME VARCHAR(100),
    TAG_VALUE CLOB,
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPKAPP_XML_LSTRM_DATA ON APP_XML_LSTRM_DATA (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC
);

ALTER TABLE APP_XML_LSTRM_DATA ADD CONSTRAINT XPK_APP_XML_LSTRM_DATA
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ
);

CREATE TABLE APP_XML_LSTRM_DATA_ATTR (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    SEQ NUMBER(10) NOT NULL,
    ATTR_NAME VARCHAR(100),
    ATTR_VALUE VARCHAR(200),
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_LSTRM_DATA_ATTR ON APP_XML_LSTRM_DATA_ATTR (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC,
    SEQ ASC
);

ALTER TABLE APP_XML_LSTRM_DATA_ATTR ADD CONSTRAINT XPK_APP_XML_LSTRM_DATA_ATTR
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ,
    SEQ
);

CREATE TABLE APP_XML_LSTRM_LIST (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    TAG_NAME VARCHAR(100),
    TAG_VALUE CLOB,
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_LSTRM_LIST ON APP_XML_LSTRM_LIST (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC
);

ALTER TABLE APP_XML_LSTRM_LIST ADD CONSTRAINT XPK_APP_XML_LSTRM_LIST
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ
);

CREATE TABLE APP_XML_LSTRM_LIST_ATTR (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    SEQ NUMBER(10) NOT NULL,
    ATTR_NAME VARCHAR(100),
    ATTR_VALUE VARCHAR(200),
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_LSTRM_LIST_ATTR ON APP_XML_LSTRM_LIST_ATTR (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC,
    SEQ ASC
);

ALTER TABLE APP_XML_LSTRM_LIST_ATTR ADD CONSTRAINT XPK_APP_XML_LSTRM_LIST_ATTR
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ,
    SEQ
);

CREATE TABLE APP_XML_OLDNEW_DATA (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    TAG_NAME VARCHAR(100),
    TAG_VALUE CLOB,
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_OLDNEW_DATA ON APP_XML_OLDNEW_DATA (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC
);

ALTER TABLE APP_XML_OLDNEW_DATA ADD CONSTRAINT XPK_APP_XML_OLDNEW_DATA
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ
);

CREATE TABLE APP_XML_OLDNEW_DATA_ATTR (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    SEQ NUMBER(10) NOT NULL,
    ATTR_NAME VARCHAR(100),
    ATTR_VALUE VARCHAR(200),
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_OLDNEW_DATA_ATTR ON APP_XML_OLDNEW_DATA_ATTR (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC,
    SEQ ASC
);

ALTER TABLE APP_XML_OLDNEW_DATA_ATTR ADD CONSTRAINT XPK_APP_XML_OLDNEW_DATA_ATTR
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ,
    SEQ
);

CREATE TABLE APP_XML_OLDNEW_LIST (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    TAG_NAME VARCHAR(100),
    TAG_VALUE CLOB,
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_OLDNEW_LIST ON APP_XML_OLDNEW_LIST (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC
);

ALTER TABLE APP_XML_OLDNEW_LIST ADD CONSTRAINT XPK_APP_XML_OLDNEW_LIST
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ
);

CREATE TABLE APP_XML_OLDNEW_LIST_ATTR (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    SEQ NUMBER(10) NOT NULL,
    ATTR_NAME VARCHAR(100),
    ATTR_VALUE VARCHAR(200),
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_OLDNEW_LIST_ATTR ON APP_XML_OLDNEW_LIST_ATTR (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC,
    SEQ ASC
);

ALTER TABLE APP_XML_OLDNEW_LIST_ATTR ADD CONSTRAINT XPK_APP_XML_OLDNEW_LIST_ATTR
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ,
    SEQ
);

CREATE TABLE APP_XML_PREC_DATA (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    TAG_NAME VARCHAR(100),
    TAG_VALUE CLOB,
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_PREC_DATA ON APP_XML_PREC_DATA (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC
);

ALTER TABLE APP_XML_PREC_DATA ADD CONSTRAINT XPK_APP_XML_PREC_DATA
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ
);

CREATE TABLE APP_XML_PREC_DATA_ATTR (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    SEQ NUMBER(10) NOT NULL,
    ATTR_NAME VARCHAR(100),
    ATTR_VALUE VARCHAR(200),
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_PREC_DATA_ATTR ON APP_XML_PREC_DATA_ATTR (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC,
    SEQ ASC
);

ALTER TABLE APP_XML_PREC_DATA_ATTR ADD CONSTRAINT XPK_APP_XML_PREC_DATA_ATTR
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ,
    SEQ
);

CREATE TABLE APP_XML_PREC_LIST (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    TAG_NAME VARCHAR(100),
    TAG_VALUE CLOB,
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_PREC_LIST ON APP_XML_PREC_LIST (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC
);

ALTER TABLE APP_XML_PREC_LIST ADD CONSTRAINT XPK_APP_XML_PREC_LIST
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ
);

CREATE TABLE APP_XML_PREC_LIST_ATTR (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    SEQ NUMBER(10) NOT NULL,
    ATTR_NAME VARCHAR(100),
    ATTR_VALUE VARCHAR(200),
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_PREC_LIST_ATTR ON APP_XML_PREC_LIST_ATTR (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC,
    SEQ ASC
);

ALTER TABLE APP_XML_PREC_LIST_ATTR ADD CONSTRAINT XPK_APP_XML_PREC_LIST_ATTR
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ,
    SEQ
);

CREATE TABLE APP_XML_THDCMP_DATA (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    TAG_NAME VARCHAR(100),
    TAG_VALUE CLOB,
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPKAPP_XML_THDCMP_DATA ON APP_XML_THDCMP_DATA (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC
);

ALTER TABLE APP_XML_THDCMP_DATA ADD CONSTRAINT XPK_APP_XML_THDCMP_DATA
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ
);

CREATE TABLE APP_XML_THDCMP_DATA_ATTR (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    SEQ NUMBER(10) NOT NULL,
    ATTR_NAME VARCHAR(100),
    ATTR_VALUE VARCHAR(200),
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_THDCMP_DATA_ATTR ON APP_XML_THDCMP_DATA_ATTR (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC,
    SEQ ASC
);

ALTER TABLE APP_XML_THDCMP_DATA_ATTR ADD CONSTRAINT XPK_APP_XML_THDCMP_DATA_ATTR
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ,
    SEQ
);

CREATE TABLE APP_XML_THDCMP_LIST (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    TAG_NAME VARCHAR(100),
    TAG_VALUE CLOB,
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_THDCMP_LIST ON APP_XML_THDCMP_LIST (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC
);

ALTER TABLE APP_XML_THDCMP_LIST ADD CONSTRAINT XPK_APP_XML_THDCMP_LIST
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ
);

CREATE TABLE APP_XML_THDCMP_LIST_ATTR (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    SEQ NUMBER(10) NOT NULL,
    ATTR_NAME VARCHAR(100),
    ATTR_VALUE VARCHAR(200),
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_THDCMP_LIST_ATTR ON APP_XML_THDCMP_LIST_ATTR (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC,
    SEQ ASC
);

ALTER TABLE APP_XML_THDCMP_LIST_ATTR ADD CONSTRAINT XPK_APP_XML_THDCMP_LIST_ATTR
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ,
    SEQ
);

CREATE TABLE APP_XML_TRTY_DATA (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    TAG_NAME VARCHAR(100),
    TAG_VALUE CLOB,
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPKAPP_XML_TRTY_DATA ON APP_XML_TRTY_DATA (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC
);

ALTER TABLE APP_XML_TRTY_DATA ADD CONSTRAINT XPK_APP_XML_TRTY_DATA
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ
);

CREATE TABLE APP_XML_TRTY_DATA_ATTR (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    SEQ NUMBER(10) NOT NULL,
    ATTR_NAME VARCHAR(100),
    ATTR_VALUE VARCHAR(200),
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_TRTY_DATA_ATTR ON APP_XML_TRTY_DATA_ATTR (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC,
    SEQ ASC
);

ALTER TABLE APP_XML_TRTY_DATA_ATTR ADD CONSTRAINT XPK_APP_XML_TRTY_DATA_ATTR
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ,
    SEQ
);

CREATE TABLE APP_XML_TRTY_LIST (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    TAG_NAME VARCHAR(100),
    TAG_VALUE CLOB,
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_TRTY_LIST ON APP_XML_TRTY_LIST (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC
)
;

ALTER TABLE APP_XML_TRTY_LIST ADD CONSTRAINT XPK_APP_XML_TRTY_LIST
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ
);

CREATE TABLE APP_XML_TRTY_LIST_ATTR (
    ROW_KEY VARCHAR(50) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    NUM NUMBER(10) NOT NULL,
    TOTAL_SEQ NUMBER(10) NOT NULL,
    SEQ NUMBER(10) NOT NULL,
    ATTR_NAME VARCHAR(100),
    ATTR_VALUE VARCHAR(200),
    CREATE_DATETIME DATE
);

CREATE UNIQUE INDEX XPK_APP_XML_TRTY_LIST_ATTR ON APP_XML_TRTY_LIST_ATTR (
    ROW_KEY ASC,
    DEPTH ASC,
    NUM ASC,
    TOTAL_SEQ ASC,
    SEQ ASC
);

ALTER TABLE APP_XML_TRTY_LIST_ATTR ADD CONSTRAINT XPK_APP_XML_TRTY_LIST_ATTR
PRIMARY KEY (
    ROW_KEY,
    DEPTH,
    NUM,
    TOTAL_SEQ,
    SEQ
);

COMMENT ON TABLE APP_ROW_KEY IS '스케줄과 데이터 키 관리';
COMMENT ON TABLE APP_XML_ADMRUL_DATA IS '행정규칙-본문-행정규칙본문조회';
COMMENT ON TABLE APP_XML_ADMRUL_DATA_ATTR IS '행정규칙-본문-행정규칙본문조회 속성정보';
COMMENT ON TABLE APP_XML_ADMRUL_LIST IS '행정규칙-본문-행정규칙목록조회';
COMMENT ON TABLE APP_XML_ADMRUL_LIST_ATTR IS '행정규칙-본문-행정규칙목록조회 속성정보';
COMMENT ON TABLE APP_XML_DETC_DATA IS '헌재결정례-본문-현재결정례본문조회';
COMMENT ON TABLE APP_XML_DETC_DATA_ATTR IS '헌재결정례-본문-현재결정례본문조회 속성정보';
COMMENT ON TABLE APP_XML_DETC_LIST IS '헌재결정례-본문-현재결정례목록조회';
COMMENT ON TABLE APP_XML_DETC_LIST_ATTR IS '헌재결정례-본문-현재결정례목록조회 속성정보';
COMMENT ON TABLE APP_XML_EFLAW_DATA IS '법령-본문-법령연혁본문조회(시행일법령본문조회)';
COMMENT ON TABLE APP_XML_EFLAW_DATA_ATTR IS '법령-본문-법령연혁본문조회(시행일법령본문조회) 속성정보';
COMMENT ON TABLE APP_XML_EFLAW_LIST IS '법령-본문-법령연혁목록조회(시행일법령목록조회)';
COMMENT ON TABLE APP_XML_EFLAW_LIST_ATTR IS '법령-본문-법령연혁목록조회(시행일법령목록조회) 속성정보';
COMMENT ON TABLE APP_XML_ELAW_DATA IS '법령-영문법령-영문법령본문조회';
COMMENT ON TABLE APP_XML_ELAW_DATA_ATTR IS '법령-영문법령-영문법령본문조회 속성정보';
COMMENT ON TABLE APP_XML_ELAW_LIST IS '법령-영문법령-영문법령목록조회';
COMMENT ON TABLE APP_XML_ELAW_LIST_ATTR IS '법령-영문법령-영문법령목록조회 속성정보';
COMMENT ON TABLE APP_XML_EXPC_DATA IS '법령해석례-본문-법령해석례본문조회';
COMMENT ON TABLE APP_XML_EXPC_DATA_ATTR IS '법령해석례-본문-법령해석례본문조회 속성정보';
COMMENT ON TABLE APP_XML_EXPC_LIST IS '법령해석례-본문-법령해석례목록조회';
COMMENT ON TABLE APP_XML_EXPC_LIST_ATTR IS '법령해석례-본문-법령해석례목록조회 속성정보';
COMMENT ON TABLE APP_XML_LSTRM_DATA IS '법령용어-본분-법령용어본문조회';
COMMENT ON TABLE APP_XML_LSTRM_DATA_ATTR IS '법령용어-본분-법령용어본문조회 속성정보';
COMMENT ON TABLE APP_XML_LSTRM_LIST IS '법령용어-본분-법령용어목록조회';
COMMENT ON TABLE APP_XML_LSTRM_LIST_ATTR IS '법령용어-본분-법령용어목록조회 속성정보';
COMMENT ON TABLE APP_XML_OLDNEW_DATA IS '법령-부가서비스-신구법본문조회';
COMMENT ON TABLE APP_XML_OLDNEW_DATA_ATTR IS '법령-부가서비스-신구법본문조회 속성정보';
COMMENT ON TABLE APP_XML_OLDNEW_LIST IS '법령-부가서비스-신구법목록조회';
COMMENT ON TABLE APP_XML_OLDNEW_LIST_ATTR IS '법령-부가서비스-신구법목록조회 속성정보';
COMMENT ON TABLE APP_XML_PREC_DATA IS '판례-본문-판례본문조회';
COMMENT ON TABLE APP_XML_PREC_DATA_ATTR IS '판례-본문-판례본문조회 속성정보';
COMMENT ON TABLE APP_XML_PREC_LIST IS '판례-본문-판례목록조회';
COMMENT ON TABLE APP_XML_PREC_LIST_ATTR IS '판례-본문-판례목록조회 속성정보';
COMMENT ON TABLE APP_XML_THDCMP_DATA IS '법령-부가서비스-3단비교본문조회';
COMMENT ON TABLE APP_XML_THDCMP_DATA_ATTR IS '법령-부가서비스-3단비교본문조회 속성정보';
COMMENT ON TABLE APP_XML_THDCMP_LIST IS '법령-부가서비스-3단비교목록조회';
COMMENT ON TABLE APP_XML_THDCMP_LIST_ATTR IS '법령-부가서비스-3단비교목록조회 속성정보';
COMMENT ON TABLE APP_XML_TRTY_DATA IS '조약-본문-조약본문조회';
COMMENT ON TABLE APP_XML_TRTY_DATA_ATTR IS '조약-본문-조약본문조회 속성정보';
COMMENT ON TABLE APP_XML_TRTY_LIST IS '조약-본문-조약목록조회';
COMMENT ON TABLE APP_XML_TRTY_LIST_ATTR IS '조약-본문-조약목록조회 속성정보';


COMMENT ON COLUMN APP_ROW_KEY.SCHED_KEY IS '스케줄 키';
COMMENT ON COLUMN APP_ROW_KEY.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_ADMRUL_DATA.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_ADMRUL_DATA.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_ADMRUL_DATA.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_ADMRUL_DATA.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_ADMRUL_DATA.TAG_NAME IS 'TAG 명';
COMMENT ON COLUMN APP_XML_ADMRUL_DATA.TAG_VALUE IS 'TAG 값';
COMMENT ON COLUMN APP_XML_ADMRUL_DATA.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_ADMRUL_DATA_ATTR.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_ADMRUL_DATA_ATTR.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_ADMRUL_DATA_ATTR.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_ADMRUL_DATA_ATTR.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_ADMRUL_DATA_ATTR.SEQ IS '노드의 Attribute 순서';
COMMENT ON COLUMN APP_XML_ADMRUL_DATA_ATTR.ATTR_NAME IS 'Attribute 명';
COMMENT ON COLUMN APP_XML_ADMRUL_DATA_ATTR.ATTR_VALUE IS 'Attribute 값';
COMMENT ON COLUMN APP_XML_ADMRUL_DATA_ATTR.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_ADMRUL_LIST.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_ADMRUL_LIST.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_ADMRUL_LIST.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_ADMRUL_LIST.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_ADMRUL_LIST.TAG_NAME IS 'TAG 명';
COMMENT ON COLUMN APP_XML_ADMRUL_LIST.TAG_VALUE IS 'TAG 값';
COMMENT ON COLUMN APP_XML_ADMRUL_LIST.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_ADMRUL_LIST_ATTR.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_ADMRUL_LIST_ATTR.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_ADMRUL_LIST_ATTR.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_ADMRUL_LIST_ATTR.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_ADMRUL_LIST_ATTR.SEQ IS '노드의 Attribute 순서';
COMMENT ON COLUMN APP_XML_ADMRUL_LIST_ATTR.ATTR_NAME IS 'Attribute 명';
COMMENT ON COLUMN APP_XML_ADMRUL_LIST_ATTR.ATTR_VALUE IS 'Attribute 값';
COMMENT ON COLUMN APP_XML_ADMRUL_LIST_ATTR.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_DETC_DATA.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_DETC_DATA.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_DETC_DATA.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_DETC_DATA.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_DETC_DATA.TAG_NAME IS 'TAG 명';
COMMENT ON COLUMN APP_XML_DETC_DATA.TAG_VALUE IS 'TAG 값';
COMMENT ON COLUMN APP_XML_DETC_DATA.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_DETC_DATA_ATTR.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_DETC_DATA_ATTR.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_DETC_DATA_ATTR.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_DETC_DATA_ATTR.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_DETC_DATA_ATTR.SEQ IS '노드의 Attribute 순서';
COMMENT ON COLUMN APP_XML_DETC_DATA_ATTR.ATTR_NAME IS 'Attribute 명';
COMMENT ON COLUMN APP_XML_DETC_DATA_ATTR.ATTR_VALUE IS 'Attribute 값';
COMMENT ON COLUMN APP_XML_DETC_DATA_ATTR.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_DETC_LIST.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_DETC_LIST.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_DETC_LIST.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_DETC_LIST.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_DETC_LIST.TAG_NAME IS 'TAG 명';
COMMENT ON COLUMN APP_XML_DETC_LIST.TAG_VALUE IS 'TAG 값';
COMMENT ON COLUMN APP_XML_DETC_LIST.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_DETC_LIST_ATTR.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_DETC_LIST_ATTR.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_DETC_LIST_ATTR.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_DETC_LIST_ATTR.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_DETC_LIST_ATTR.SEQ IS '노드의 Attribute 순서';
COMMENT ON COLUMN APP_XML_DETC_LIST_ATTR.ATTR_NAME IS 'Attribute 명';
COMMENT ON COLUMN APP_XML_DETC_LIST_ATTR.ATTR_VALUE IS 'Attribute 값';
COMMENT ON COLUMN APP_XML_DETC_LIST_ATTR.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_EFLAW_DATA.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_EFLAW_DATA.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_EFLAW_DATA.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_EFLAW_DATA.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_EFLAW_DATA.TAG_NAME IS 'TAG 명';
COMMENT ON COLUMN APP_XML_EFLAW_DATA.TAG_VALUE IS 'TAG 값';
COMMENT ON COLUMN APP_XML_EFLAW_DATA.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_EFLAW_DATA_ATTR.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_EFLAW_DATA_ATTR.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_EFLAW_DATA_ATTR.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_EFLAW_DATA_ATTR.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_EFLAW_DATA_ATTR.SEQ IS '노드의 Attribute 순서';
COMMENT ON COLUMN APP_XML_EFLAW_DATA_ATTR.ATTR_NAME IS 'Attribute 명';
COMMENT ON COLUMN APP_XML_EFLAW_DATA_ATTR.ATTR_VALUE IS 'Attribute 값';
COMMENT ON COLUMN APP_XML_EFLAW_DATA_ATTR.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_EFLAW_LIST.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_EFLAW_LIST.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_EFLAW_LIST.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_EFLAW_LIST.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_EFLAW_LIST.TAG_NAME IS 'TAG 명';
COMMENT ON COLUMN APP_XML_EFLAW_LIST.TAG_VALUE IS 'TAG 값';
COMMENT ON COLUMN APP_XML_EFLAW_LIST.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_EFLAW_LIST_ATTR.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_EFLAW_LIST_ATTR.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_EFLAW_LIST_ATTR.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_EFLAW_LIST_ATTR.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_EFLAW_LIST_ATTR.SEQ IS '노드의 Attribute 순서';
COMMENT ON COLUMN APP_XML_EFLAW_LIST_ATTR.ATTR_NAME IS 'Attribute 명';
COMMENT ON COLUMN APP_XML_EFLAW_LIST_ATTR.ATTR_VALUE IS 'Attribute 값';
COMMENT ON COLUMN APP_XML_EFLAW_LIST_ATTR.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_ELAW_DATA.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_ELAW_DATA.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_ELAW_DATA.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_ELAW_DATA.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_ELAW_DATA.TAG_NAME IS 'TAG 명';
COMMENT ON COLUMN APP_XML_ELAW_DATA.TAG_VALUE IS 'TAG 값';
COMMENT ON COLUMN APP_XML_ELAW_DATA.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_ELAW_DATA_ATTR.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_ELAW_DATA_ATTR.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_ELAW_DATA_ATTR.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_ELAW_DATA_ATTR.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_ELAW_DATA_ATTR.SEQ IS '노드의 Attribute 순서';
COMMENT ON COLUMN APP_XML_ELAW_DATA_ATTR.ATTR_NAME IS 'Attribute 명';
COMMENT ON COLUMN APP_XML_ELAW_DATA_ATTR.ATTR_VALUE IS 'Attribute 값';
COMMENT ON COLUMN APP_XML_ELAW_DATA_ATTR.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_ELAW_LIST.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_ELAW_LIST.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_ELAW_LIST.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_ELAW_LIST.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_ELAW_LIST.TAG_NAME IS 'TAG 명';
COMMENT ON COLUMN APP_XML_ELAW_LIST.TAG_VALUE IS 'TAG 값';
COMMENT ON COLUMN APP_XML_ELAW_LIST.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_ELAW_LIST_ATTR.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_ELAW_LIST_ATTR.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_ELAW_LIST_ATTR.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_ELAW_LIST_ATTR.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_ELAW_LIST_ATTR.SEQ IS '노드의 Attribute 순서';
COMMENT ON COLUMN APP_XML_ELAW_LIST_ATTR.ATTR_NAME IS 'Attribute 명';
COMMENT ON COLUMN APP_XML_ELAW_LIST_ATTR.ATTR_VALUE IS 'Attribute 값';
COMMENT ON COLUMN APP_XML_ELAW_LIST_ATTR.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_EXPC_DATA.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_EXPC_DATA.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_EXPC_DATA.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_EXPC_DATA.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_EXPC_DATA.TAG_NAME IS 'TAG 명';
COMMENT ON COLUMN APP_XML_EXPC_DATA.TAG_VALUE IS 'TAG 값';
COMMENT ON COLUMN APP_XML_EXPC_DATA.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_EXPC_DATA_ATTR.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_EXPC_DATA_ATTR.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_EXPC_DATA_ATTR.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_EXPC_DATA_ATTR.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_EXPC_DATA_ATTR.SEQ IS '노드의 Attribute 순서';
COMMENT ON COLUMN APP_XML_EXPC_DATA_ATTR.ATTR_NAME IS 'Attribute 명';
COMMENT ON COLUMN APP_XML_EXPC_DATA_ATTR.ATTR_VALUE IS 'Attribute 값';
COMMENT ON COLUMN APP_XML_EXPC_DATA_ATTR.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_EXPC_LIST.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_EXPC_LIST.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_EXPC_LIST.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_EXPC_LIST.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_EXPC_LIST.TAG_NAME IS 'TAG 명';
COMMENT ON COLUMN APP_XML_EXPC_LIST.TAG_VALUE IS 'TAG 값';
COMMENT ON COLUMN APP_XML_EXPC_LIST.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_EXPC_LIST_ATTR.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_EXPC_LIST_ATTR.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_EXPC_LIST_ATTR.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_EXPC_LIST_ATTR.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_EXPC_LIST_ATTR.SEQ IS '노드의 Attribute 순서';
COMMENT ON COLUMN APP_XML_EXPC_LIST_ATTR.ATTR_NAME IS 'Attribute 명';
COMMENT ON COLUMN APP_XML_EXPC_LIST_ATTR.ATTR_VALUE IS 'Attribute 값';
COMMENT ON COLUMN APP_XML_EXPC_LIST_ATTR.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_LSTRM_DATA.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_LSTRM_DATA.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_LSTRM_DATA.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_LSTRM_DATA.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_LSTRM_DATA.TAG_NAME IS 'TAG 명';
COMMENT ON COLUMN APP_XML_LSTRM_DATA.TAG_VALUE IS 'TAG 값';
COMMENT ON COLUMN APP_XML_LSTRM_DATA.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_LSTRM_DATA_ATTR.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_LSTRM_DATA_ATTR.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_LSTRM_DATA_ATTR.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_LSTRM_DATA_ATTR.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_LSTRM_DATA_ATTR.SEQ IS '노드의 Attribute 순서';
COMMENT ON COLUMN APP_XML_LSTRM_DATA_ATTR.ATTR_NAME IS 'Attribute 명';
COMMENT ON COLUMN APP_XML_LSTRM_DATA_ATTR.ATTR_VALUE IS 'Attribute 값';
COMMENT ON COLUMN APP_XML_LSTRM_DATA_ATTR.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_LSTRM_LIST.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_LSTRM_LIST.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_LSTRM_LIST.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_LSTRM_LIST.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_LSTRM_LIST.TAG_NAME IS 'TAG 명';
COMMENT ON COLUMN APP_XML_LSTRM_LIST.TAG_VALUE IS 'TAG 값';
COMMENT ON COLUMN APP_XML_LSTRM_LIST.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_LSTRM_LIST_ATTR.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_LSTRM_LIST_ATTR.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_LSTRM_LIST_ATTR.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_LSTRM_LIST_ATTR.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_LSTRM_LIST_ATTR.SEQ IS '노드의 Attribute 순서';
COMMENT ON COLUMN APP_XML_LSTRM_LIST_ATTR.ATTR_NAME IS 'Attribute 명';
COMMENT ON COLUMN APP_XML_LSTRM_LIST_ATTR.ATTR_VALUE IS 'Attribute 값';
COMMENT ON COLUMN APP_XML_LSTRM_LIST_ATTR.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_OLDNEW_DATA.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_OLDNEW_DATA.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_OLDNEW_DATA.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_OLDNEW_DATA.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_OLDNEW_DATA.TAG_NAME IS 'TAG 명';
COMMENT ON COLUMN APP_XML_OLDNEW_DATA.TAG_VALUE IS 'TAG 값';
COMMENT ON COLUMN APP_XML_OLDNEW_DATA.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_OLDNEW_DATA_ATTR.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_OLDNEW_DATA_ATTR.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_OLDNEW_DATA_ATTR.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_OLDNEW_DATA_ATTR.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_OLDNEW_DATA_ATTR.SEQ IS '노드의 Attribute 순서';
COMMENT ON COLUMN APP_XML_OLDNEW_DATA_ATTR.ATTR_NAME IS 'Attribute 명';
COMMENT ON COLUMN APP_XML_OLDNEW_DATA_ATTR.ATTR_VALUE IS 'Attribute 값';
COMMENT ON COLUMN APP_XML_OLDNEW_DATA_ATTR.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_OLDNEW_LIST.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_OLDNEW_LIST.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_OLDNEW_LIST.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_OLDNEW_LIST.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_OLDNEW_LIST.TAG_NAME IS 'TAG 명';
COMMENT ON COLUMN APP_XML_OLDNEW_LIST.TAG_VALUE IS 'TAG 값';
COMMENT ON COLUMN APP_XML_OLDNEW_LIST.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_OLDNEW_LIST_ATTR.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_OLDNEW_LIST_ATTR.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_OLDNEW_LIST_ATTR.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_OLDNEW_LIST_ATTR.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_OLDNEW_LIST_ATTR.SEQ IS '노드의 Attribute 순서';
COMMENT ON COLUMN APP_XML_OLDNEW_LIST_ATTR.ATTR_NAME IS 'Attribute 명';
COMMENT ON COLUMN APP_XML_OLDNEW_LIST_ATTR.ATTR_VALUE IS 'Attribute 값';
COMMENT ON COLUMN APP_XML_OLDNEW_LIST_ATTR.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_PREC_DATA.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_PREC_DATA.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_PREC_DATA.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_PREC_DATA.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_PREC_DATA.TAG_NAME IS 'TAG 명';
COMMENT ON COLUMN APP_XML_PREC_DATA.TAG_VALUE IS 'TAG 값';
COMMENT ON COLUMN APP_XML_PREC_DATA.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_PREC_DATA_ATTR.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_PREC_DATA_ATTR.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_PREC_DATA_ATTR.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_PREC_DATA_ATTR.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_PREC_DATA_ATTR.SEQ IS '노드의 Attribute 순서';
COMMENT ON COLUMN APP_XML_PREC_DATA_ATTR.ATTR_NAME IS 'Attribute 명';
COMMENT ON COLUMN APP_XML_PREC_DATA_ATTR.ATTR_VALUE IS 'Attribute 값';
COMMENT ON COLUMN APP_XML_PREC_DATA_ATTR.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_PREC_LIST.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_PREC_LIST.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_PREC_LIST.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_PREC_LIST.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_PREC_LIST.TAG_NAME IS 'TAG 명';
COMMENT ON COLUMN APP_XML_PREC_LIST.TAG_VALUE IS 'TAG 값';
COMMENT ON COLUMN APP_XML_PREC_LIST.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_PREC_LIST_ATTR.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_PREC_LIST_ATTR.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_PREC_LIST_ATTR.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_PREC_LIST_ATTR.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_PREC_LIST_ATTR.SEQ IS '노드의 Attribute 순서';
COMMENT ON COLUMN APP_XML_PREC_LIST_ATTR.ATTR_NAME IS 'Attribute 명';
COMMENT ON COLUMN APP_XML_PREC_LIST_ATTR.ATTR_VALUE IS 'Attribute 값';
COMMENT ON COLUMN APP_XML_PREC_LIST_ATTR.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_THDCMP_DATA.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_THDCMP_DATA.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_THDCMP_DATA.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_THDCMP_DATA.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_THDCMP_DATA.TAG_NAME IS 'TAG 명';
COMMENT ON COLUMN APP_XML_THDCMP_DATA.TAG_VALUE IS 'TAG 값';
COMMENT ON COLUMN APP_XML_THDCMP_DATA.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_THDCMP_DATA_ATTR.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_THDCMP_DATA_ATTR.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_THDCMP_DATA_ATTR.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_THDCMP_DATA_ATTR.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_THDCMP_DATA_ATTR.SEQ IS '노드의 Attribute 순서';
COMMENT ON COLUMN APP_XML_THDCMP_DATA_ATTR.ATTR_NAME IS 'Attribute 명';
COMMENT ON COLUMN APP_XML_THDCMP_DATA_ATTR.ATTR_VALUE IS 'Attribute 값';
COMMENT ON COLUMN APP_XML_THDCMP_DATA_ATTR.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_THDCMP_LIST.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_THDCMP_LIST.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_THDCMP_LIST.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_THDCMP_LIST.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_THDCMP_LIST.TAG_NAME IS 'TAG 명';
COMMENT ON COLUMN APP_XML_THDCMP_LIST.TAG_VALUE IS 'TAG 값';
COMMENT ON COLUMN APP_XML_THDCMP_LIST.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_THDCMP_LIST_ATTR.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_THDCMP_LIST_ATTR.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_THDCMP_LIST_ATTR.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_THDCMP_LIST_ATTR.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_THDCMP_LIST_ATTR.SEQ IS '노드의 Attribute 순서';
COMMENT ON COLUMN APP_XML_THDCMP_LIST_ATTR.ATTR_NAME IS 'Attribute 명';
COMMENT ON COLUMN APP_XML_THDCMP_LIST_ATTR.ATTR_VALUE IS 'Attribute 값';
COMMENT ON COLUMN APP_XML_THDCMP_LIST_ATTR.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_TRTY_DATA.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_TRTY_DATA.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_TRTY_DATA.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_TRTY_DATA.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_TRTY_DATA.TAG_NAME IS 'TAG 명';
COMMENT ON COLUMN APP_XML_TRTY_DATA.TAG_VALUE IS 'TAG 값';
COMMENT ON COLUMN APP_XML_TRTY_DATA.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_TRTY_DATA_ATTR.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_TRTY_DATA_ATTR.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_TRTY_DATA_ATTR.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_TRTY_DATA_ATTR.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_TRTY_DATA_ATTR.SEQ IS '노드의 Attribute 순서';
COMMENT ON COLUMN APP_XML_TRTY_DATA_ATTR.ATTR_NAME IS 'Attribute 명';
COMMENT ON COLUMN APP_XML_TRTY_DATA_ATTR.ATTR_VALUE IS 'Attribute 값';
COMMENT ON COLUMN APP_XML_TRTY_DATA_ATTR.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_TRTY_LIST.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_TRTY_LIST.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_TRTY_LIST.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_TRTY_LIST.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_TRTY_LIST.TAG_NAME IS 'TAG 명';
COMMENT ON COLUMN APP_XML_TRTY_LIST.TAG_VALUE IS 'TAG 값';
COMMENT ON COLUMN APP_XML_TRTY_LIST.CREATE_DATETIME IS '생성 일시';
COMMENT ON COLUMN APP_XML_TRTY_LIST_ATTR.ROW_KEY IS '데이터 키';
COMMENT ON COLUMN APP_XML_TRTY_LIST_ATTR.DEPTH IS 'XML 노드 depth';
COMMENT ON COLUMN APP_XML_TRTY_LIST_ATTR.NUM IS '같은 노드 순서';
COMMENT ON COLUMN APP_XML_TRTY_LIST_ATTR.TOTAL_SEQ IS '전체 순서';
COMMENT ON COLUMN APP_XML_TRTY_LIST_ATTR.SEQ IS '노드의 Attribute 순서';
COMMENT ON COLUMN APP_XML_TRTY_LIST_ATTR.ATTR_NAME IS 'Attribute 명';
COMMENT ON COLUMN APP_XML_TRTY_LIST_ATTR.ATTR_VALUE IS 'Attribute 값';
COMMENT ON COLUMN APP_XML_TRTY_LIST_ATTR.CREATE_DATETIME IS '생성 일시';

-- 환경설정:
-- 1. 첨부파일 위치
--   - 파일명: application.yaml
--   - 추가 및 변경: scvconfig:
--   - file-path: "C:/home/file"
--   - custom-url: "https://www.law.go.kr"
-- 2. 첨부파일 추가 정보
--   - application.yaml파일의 scvconfig 에 있는 file-path의 위치
--   - 각 테이블의 row-key 디렉토리에 각 파일의 url에 있는 일련번호로 파일 저장
